//! The cookie rules: what a `Set-Cookie` says, which host may set it, and
//! which request carries it back.
//!
//! This file does no I/O and it holds no cookie. It takes bytes and
//! returns values, the way every other file in `zurl-core` does.
//! `lib/zurl/Jar.zig` owns the store, the file, and the memory.
//!
//! **A jar is a credential store.** A cookie is a bearer token: whoever
//! holds it is the session. So the rules below are a security boundary,
//! not a formatting question, and each one is written here once so that
//! the store cannot answer any of them a second way.
//!
//! Four rules decide whether a cookie goes on the wire, and this file owns
//! all four:
//!
//! - **Domain.** `domainMatches` sends a cookie to the host that set it,
//!   and to a subdomain of that host when the cookie is not host-only.
//! - **Path.** `pathMatches` sends a cookie to the path it names and to
//!   what sits under that path.
//! - **Secure.** `secureContext` reports whether the hop can carry a
//!   `Secure` cookie at all.
//! - **Expiry.** A cookie whose `expires` has passed is not sent, and it
//!   is not kept.
//!
//! One more rule decides whether a response may set a cookie at all:
//! `resolveDomain`. A response from `evil.example` must not be able to
//! set a cookie that a later request sends to `bank.example`.
//!
//! **Every bound here is on untrusted input.** A `Set-Cookie` comes from a
//! server and a jar file comes from the disk, so both are attacker-shaped.
//! The names below cap each field, and `lib/zurl/Jar.zig` caps the count
//! and the file size.

const std = @import("std");
const Url = @import("url.zig").Url;
const psl = @import("psl.zig");

/// The largest cookie name this build keeps, in bytes.
///
/// A name is a token in a header, and a real one is short. curl 8.21.0
/// caps a name and a value together at 5000 bytes and refuses the whole
/// `Set-Cookie` past that. zurl caps each field on its own so a fault
/// message can say which field was too long.
pub const name_len_max: usize = 512;

/// The largest cookie value this build keeps, in bytes.
///
/// Large enough for a signed session token, which is the longest value a
/// real server sends. A value past this is refused whole: a cookie cut in
/// half is a different credential, and sending it would look to the server
/// like a session that never existed.
pub const value_len_max: usize = 4096;

/// The largest cookie domain this build keeps, in bytes.
///
/// A DNS name is at most 253 bytes, so 256 covers every domain a real
/// server can name and refuses text that is not a domain at all.
pub const domain_len_max: usize = 256;

/// The largest cookie path this build keeps, in bytes.
pub const path_len_max: usize = 1024;

/// The largest `Set-Cookie` header value this build reads, in bytes.
///
/// A header longer than this is refused whole, before any field of it is
/// parsed. The four field bounds above already add up to less than this,
/// so a `Set-Cookie` that fits here can still be refused for one field.
pub const set_cookie_len_max: usize = 8192;

/// The largest `Cookie` request header this build writes, in bytes.
///
/// A jar that matches more cookies than fit stops at this bound and the
/// store reports how many it dropped. Recovery is never silent: a request
/// that carried half the session must not look like a request that carried
/// all of it.
pub const header_len_max: usize = 8192;

/// The longest life a cookie may have, in seconds. 400 days.
///
/// **A cookie is a credential, so its life is bounded.** A server that
/// asks for an expiry in the year 2100 gets one 400 days out instead. RFC
/// 6265bis section 5.5 lets a client do this, and every browser does.
///
/// Measured against curl 8.21.0, which does the same: a `Set-Cookie` with
/// `Expires=Wed, 09 Jun 2100 10:18:14 GMT` reached the jar with an expiry
/// exactly 400 days after the request, and not the year 2100.
pub const lifetime_max_s: i64 = 400 * 24 * 60 * 60;

/// The three comment lines and the empty line that start a Netscape cookie
/// file.
///
/// Measured against curl 8.21.0: `curl -c jar` writes exactly these four
/// lines, and it writes them even when the jar holds no cookie. The first
/// two lines are byte for byte what curl writes. The third names zurl,
/// because zurl wrote the file and libcurl did not.
pub const jar_header =
    "# Netscape HTTP Cookie File\n" ++
    "# https://curl.se/docs/http-cookies.html\n" ++
    "# This file was generated by zurl! Edit at your own risk.\n" ++
    "\n";

/// What curl puts in front of the domain column of a `HttpOnly` cookie.
///
/// The line is a comment to any reader that does not know the convention,
/// so an old reader drops the cookie rather than reads it wrong. curl
/// writes it and reads it back, and zurl does the same, so a jar can move
/// between the two programs.
pub const http_only_prefix = "#HttpOnly_";

/// Every reason a `Set-Cookie` header does not become a cookie.
///
/// Each name says which rule refused it. The store counts them and reports
/// the count, so a transfer that dropped a cookie does not look like one
/// the server never sent a cookie to.
pub const Refusal = error{
    /// The header carries no `name=value` pair at all.
    CookieMalformed,
    /// A field of the cookie is longer than the bound above it.
    CookieTooLarge,
    /// The `Domain` attribute names a host that this response does not
    /// control. This is the rule that stops `evil.example` setting a
    /// cookie for `bank.example`.
    CookieDomainNotOwned,
    /// The `Domain` attribute names a domain no single site owns: one
    /// label, such as `com` or `localhost`, or a public suffix of the list
    /// in `zurl_core.psl`, such as `co.uk`.
    ///
    /// A cookie on such a domain would go to every host under it. See
    /// `resolveDomain` rules 3 and 6.
    CookiePublicSuffix,
    /// The cookie has already expired, so nothing would ever send it.
    CookieExpired,
};

/// What one `Set-Cookie` header said, with every slice borrowed from the
/// header text.
///
/// This is what the peer wrote and not what the jar keeps. `resolveDomain`
/// and `resolvePath` turn it into the domain and the path a cookie is
/// stored under.
pub const Attributes = struct {
    name: []const u8,
    value: []const u8,
    /// The `Domain` attribute with one leading dot taken off, or null when
    /// the header named none. Never empty: an empty attribute reads as one
    /// the header did not name, which is RFC 6265 section 5.2.3.
    domain: ?[]const u8 = null,
    /// The `Path` attribute, or null when the header named none or named
    /// one that does not start with a slash. RFC 6265 section 5.2.4 tells
    /// a client to ignore such a path and use the default one.
    path: ?[]const u8 = null,
    /// The `Expires` attribute as seconds since the epoch, or null when
    /// the header named none or named a date this build cannot read.
    expires: ?i64 = null,
    /// The `Max-Age` attribute in seconds, or null when the header named
    /// none or named one that is not a number.
    ///
    /// May be zero or negative. RFC 6265 section 5.2.2 says such a value
    /// expires the cookie at once, which deletes it.
    max_age: ?i64 = null,
    secure: bool = false,
    http_only: bool = false,
};

/// What the store keeps for one cookie, once the rules have run.
pub const Resolved = struct {
    name: []const u8,
    value: []const u8,
    /// The domain the cookie is stored under, with no leading dot.
    domain: []const u8,
    path: []const u8,
    /// Whether the cookie goes to that one host and to no subdomain of it.
    host_only: bool,
    secure: bool,
    http_only: bool,
    /// When the cookie stops being valid, in seconds since the epoch.
    /// Null for a session cookie, which lasts as long as the run.
    expires: ?i64,
};

/// Reads one `Set-Cookie` header value.
///
/// `text` is the value alone, with no `Set-Cookie:` in front of it. Every
/// slice of the answer borrows from `text`.
///
/// The parse follows RFC 6265 section 5.2: the text up to the first `;` is
/// the `name=value` pair, and each `;`-separated piece after it is one
/// attribute. Spaces around a name and around a value are dropped, which
/// is what section 5.2 step 3 asks for.
///
/// A pair with no `=` at all is `error.CookieMalformed`. Measured against
/// curl 8.21.0: `Set-Cookie: novalue` sets no cookie and reaches no jar.
/// A pair with an empty value is a cookie, and curl keeps it.
///
/// An attribute this build does not know is dropped without a fault, which
/// RFC 6265 section 5.2 step 4 requires: a server may send an attribute
/// from a later specification, and a client that refused the cookie for it
/// would drop a session over a name it simply had not learned.
pub fn parseSetCookie(text: []const u8) Refusal!Attributes {
    if (text.len > set_cookie_len_max) return error.CookieTooLarge;

    const pair_end = std.mem.indexOfScalar(u8, text, ';') orelse text.len;
    const pair = text[0..pair_end];
    const equals = std.mem.indexOfScalar(u8, pair, '=') orelse return error.CookieMalformed;

    const name = std.mem.trim(u8, pair[0..equals], " \t");
    const value = std.mem.trim(u8, pair[equals + 1 ..], " \t");
    if (name.len == 0) return error.CookieMalformed;
    if (name.len > name_len_max) return error.CookieTooLarge;
    if (value.len > value_len_max) return error.CookieTooLarge;

    var attrs: Attributes = .{ .name = name, .value = value };

    // The bound on this loop is the length of the text, because every
    // round consumes at least the separator it found. `set_cookie_len_max`
    // above already bounds that length, so the loop is bounded twice.
    var rest = if (pair_end < text.len) text[pair_end + 1 ..] else "";
    while (rest.len != 0) {
        const end = std.mem.indexOfScalar(u8, rest, ';') orelse rest.len;
        const piece = std.mem.trim(u8, rest[0..end], " \t");
        rest = if (end < rest.len) rest[end + 1 ..] else "";
        if (piece.len == 0) continue;

        const split = std.mem.indexOfScalar(u8, piece, '=');
        const attr_name = std.mem.trim(u8, if (split) |i| piece[0..i] else piece, " \t");
        const attr_value = std.mem.trim(u8, if (split) |i| piece[i + 1 ..] else "", " \t");

        if (std.ascii.eqlIgnoreCase(attr_name, "Secure")) {
            attrs.secure = true;
        } else if (std.ascii.eqlIgnoreCase(attr_name, "HttpOnly")) {
            attrs.http_only = true;
        } else if (std.ascii.eqlIgnoreCase(attr_name, "Domain")) {
            // One leading dot comes off here. RFC 6265 section 5.2.3 says
            // to ignore it, and curl writes the dot back on its own when
            // it saves a jar. An attribute that is a dot alone, or empty,
            // reads as one the header never named.
            const raw = if (attr_value.len != 0 and attr_value[0] == '.') attr_value[1..] else attr_value;
            attrs.domain = if (raw.len == 0) null else raw;
        } else if (std.ascii.eqlIgnoreCase(attr_name, "Path")) {
            // A path that does not start with a slash is not a path. RFC
            // 6265 section 5.2.4 tells a client to use the default path
            // instead, so this leaves the field null.
            attrs.path = if (attr_value.len != 0 and attr_value[0] == '/') attr_value else null;
        } else if (std.ascii.eqlIgnoreCase(attr_name, "Max-Age")) {
            attrs.max_age = std.fmt.parseInt(i64, attr_value, 10) catch null;
        } else if (std.ascii.eqlIgnoreCase(attr_name, "Expires")) {
            attrs.expires = parseDate(attr_value);
        }
    }

    return attrs;
}

/// Whether `host` is an IP address rather than a name.
///
/// A cookie may never be set for a superset of an address: `192.0.2.1`
/// owns no subdomain, so an address host gets host-only cookies and
/// nothing else. Measured against curl 8.21.0: a `Set-Cookie` from
/// `127.0.0.1` with `Domain=127.0.0.1` reaches the jar with `FALSE` in the
/// include-subdomains column, which is a host-only cookie.
///
/// The test is deliberately loose. Anything that parses as an IPv4 or IPv6
/// address is an address, and so is anything holding a colon, because a
/// name may not hold one. A host this calls an address gets the stricter
/// rule, so a wrong answer here costs a cookie and never leaks one.
pub fn isIpLiteral(host: []const u8) bool {
    if (std.mem.indexOfScalar(u8, host, ':') != null) return true;
    return ip4Octets(host) != null;
}

/// Reads `host` as a dotted-quad IPv4 literal, or null when it is not one.
///
/// Written here rather than taken from `std.Io.net`, because this package
/// does no I/O and imports nothing that does. The form a url may carry is
/// exactly four decimal groups, so a stricter reader than the one a
/// resolver uses is the right reader here.
fn ip4Octets(host: []const u8) ?[4]u8 {
    var octets: [4]u8 = undefined;
    var it = std.mem.splitScalar(u8, host, '.');
    for (&octets) |*octet| {
        const group = it.next() orelse return null;
        if (group.len == 0 or group.len > 3) return null;
        if (!allDigits(group)) return null;
        octet.* = std.fmt.parseInt(u8, group, 10) catch return null;
    }
    if (it.next() != null) return null;
    return octets;
}

/// How many labels `domain` has, counting an empty one.
fn labelCount(domain: []const u8) usize {
    return std.mem.count(u8, domain, ".") + 1;
}

/// Whether `host` is `domain` or sits under it.
///
/// RFC 6265 section 5.1.3. `host` matches when it equals `domain`, and
/// when it ends with `domain` behind a dot. So `a.example.com` matches
/// `example.com`, and `notexample.com` does not.
///
/// `host_only` narrows it to equality alone, which is the whole meaning of
/// a host-only cookie: the host that set it gets it back, and no
/// subdomain does.
///
/// Compared without regard to case, because DNS names are
/// case-insensitive and a redirect may name the same host in another case.
///
/// An address host matches on equality alone, whatever `host_only` says.
/// `1.2.3.4` is not a subdomain of `2.3.4`, and a suffix test would say it
/// is.
pub fn domainMatches(host: []const u8, domain: []const u8, host_only: bool) bool {
    if (domain.len == 0 or host.len == 0) return false;
    if (std.ascii.eqlIgnoreCase(host, domain)) return true;
    if (host_only) return false;
    if (isIpLiteral(host)) return false;
    if (host.len <= domain.len) return false;
    const start = host.len - domain.len;
    if (host[start - 1] != '.') return false;
    return std.ascii.eqlIgnoreCase(host[start..], domain);
}

/// Whether a request for `request_path` carries a cookie stored under
/// `cookie_path`.
///
/// RFC 6265 section 5.1.4. The paths match when they are equal, when
/// `cookie_path` ends in a slash and starts `request_path`, and when
/// `request_path` has a slash exactly where `cookie_path` ends. So a
/// cookie on `/dir` reaches `/dir` and `/dir/page`, and does not reach
/// `/directory`.
pub fn pathMatches(request_path: []const u8, cookie_path: []const u8) bool {
    if (cookie_path.len == 0) return false;
    if (std.mem.eql(u8, request_path, cookie_path)) return true;
    if (request_path.len <= cookie_path.len) return false;
    if (!std.mem.startsWith(u8, request_path, cookie_path)) return false;
    if (cookie_path[cookie_path.len - 1] == '/') return true;
    return request_path[cookie_path.len] == '/';
}

/// The path a cookie takes when its header named none.
///
/// RFC 6265 section 5.1.4: the request path up to, and not including, its
/// last slash, and `/` when that leaves nothing. Measured against curl
/// 8.21.0: a `Set-Cookie` with no `Path` from `/dir/page` reaches the jar
/// with the path `/dir`, and one from `/` reaches it with `/`.
///
/// The answer borrows from `request_path`.
pub fn defaultPath(request_path: []const u8) []const u8 {
    if (request_path.len == 0 or request_path[0] != '/') return "/";
    const last = std.mem.lastIndexOfScalar(u8, request_path, '/').?;
    if (last == 0) return "/";
    return request_path[0..last];
}

/// The domain and the host-only flag a cookie from `host` is stored under.
///
/// **This is the rule that stops one host setting a cookie for another.**
/// A response controls the host it came from and the hosts under that
/// host, and nothing else. `evil.example` therefore cannot set a cookie
/// for `bank.example`, and no host can set one for a public suffix such as
/// `com`, where every site on the internet would read it back.
///
/// The rules, in order:
///
/// 1. No `Domain` attribute gives a host-only cookie on `host` itself.
///    RFC 6265 section 5.3 step 6.
/// 2. An address host may only name itself, and the cookie is host-only.
///    An address owns no subdomain.
/// 3. A `Domain` of one label, such as `com` or `localhost`, is refused.
///    See below.
/// 4. A `Domain` that `host` does not sit under is refused. This is the
///    `evil.example` case, and it is the rule that carries the weight.
/// 5. A `Domain` that equals `host` gives a **host-only** cookie.
/// 6. A `Domain` that is a public suffix is refused. `zurl_core.psl` holds
///    the list, so this catches `co.uk`, `com.au`, and `github.io`, which
///    rule 3 cannot see.
/// 7. Anything left gives a domain cookie, which subdomains also get.
///
/// **Rule 5 is curl 8.22.0's change, taken further.** That release made
/// "cookies set for an exact PSL domain is host-only": a `Set-Cookie` from
/// `co.uk` naming `Domain=co.uk` no longer becomes a cookie that every
/// `*.co.uk` host reads. zurl applies the host-only answer to **every**
/// exact match, which covers that case and is stricter than curl
/// everywhere else: a cookie set with `Domain=www.example.com` by
/// `www.example.com` reaches that host and not `deep.www.example.com`.
/// Stricter costs a cookie. Looser leaks one.
///
/// **Rule 6 is the list, and it runs after rule 5.** One label is the
/// floor a client can hold with no list, and rule 3 is that floor. The
/// list is what names `co.uk`, `com.au`, and `github.io`, which are public
/// suffixes of two labels that a host sits under. Without it a response
/// from `www.example.co.uk` could set a cookie on `.co.uk`, and a later
/// request in the same run to another `*.co.uk` host would carry it.
/// Measured against curl 8.21.0, which refuses the same header through
/// libpsl, and which keeps `Domain=.example.co.uk` the way zurl does.
///
/// The order matters. A response from `co.uk` itself naming
/// `Domain=co.uk` reaches rule 5 first and gets a host-only cookie, which
/// is what curl 8.22.0 gives it. Only a response that wants to widen a
/// cookie onto a suffix it merely sits under reaches rule 6.
pub fn resolveDomain(host: []const u8, attribute: ?[]const u8) Refusal!struct {
    domain: []const u8,
    host_only: bool,
} {
    if (host.len == 0 or host.len > domain_len_max) return error.CookieDomainNotOwned;

    const domain = attribute orelse return .{ .domain = host, .host_only = true };
    if (domain.len > domain_len_max) return error.CookieTooLarge;

    // An address names one peer. It has no subdomain to give away, so the
    // only attribute it may carry is its own text, and the answer is
    // host-only either way.
    if (isIpLiteral(host)) {
        if (!std.ascii.eqlIgnoreCase(host, domain)) return error.CookieDomainNotOwned;
        return .{ .domain = host, .host_only = true };
    }

    if (labelCount(domain) < 2) return error.CookiePublicSuffix;

    // The host must sit under the attribute. `domainMatches` with
    // `host_only` false is exactly that test, and it is the same function
    // that decides where the cookie goes later, so a cookie can never be
    // stored under a domain it would not be sent to.
    if (!domainMatches(host, domain, false)) return error.CookieDomainNotOwned;

    if (std.ascii.eqlIgnoreCase(host, domain)) return .{ .domain = domain, .host_only = true };

    // **The public suffix list.** The host does sit under the attribute,
    // and the attribute is still a domain no site owns, so a cookie stored
    // under it would go to every other site under it. `www.example.co.uk`
    // naming `Domain=co.uk` is refused here.
    //
    // This runs after the exact match above, so a response from `co.uk`
    // itself still gets a host-only cookie rather than a refusal, which is
    // curl 8.22.0's rule. It is only the response that wants to widen a
    // cookie onto a suffix it shares that gets nothing.
    if (psl.isPublicSuffix(domain)) return error.CookiePublicSuffix;

    return .{ .domain = domain, .host_only = false };
}

/// Turns one `Set-Cookie` into the cookie a store keeps, or reports which
/// rule refused it.
///
/// `url` is the hop the header arrived on, and `now` is the time in
/// seconds since the epoch. Every slice of the answer borrows from `attrs`
/// or from `url`.
///
/// `Max-Age` outranks `Expires` when a header carries both, which is RFC
/// 6265 section 5.2.2 and what curl does. Measured against curl 8.21.0:
/// `Set-Cookie: both=b1; Max-Age=7200; Expires=<2100>` reached the jar
/// with an expiry 7200 seconds after the request, and not the year 2100.
///
/// A cookie that has already expired is `error.CookieExpired`. It is not
/// stored, because storing it would only delete whatever cookie of the
/// same name was already there. Deleting on purpose is what a server does
/// with `Max-Age=0`, and a store that wants that behaviour reads this
/// error and removes the match. Measured: curl drops a `Set-Cookie` with a
/// past `Expires` and writes no line for it.
pub fn resolve(attrs: Attributes, url: Url, now: i64) Refusal!Resolved {
    const domain = try resolveDomain(url.host, attrs.domain);

    const path = attrs.path orelse defaultPath(url.path);
    if (path.len > path_len_max) return error.CookieTooLarge;

    // Null means a session cookie: one that lasts until the run ends.
    const asked: ?i64 = if (attrs.max_age) |seconds|
        std.math.add(i64, now, seconds) catch std.math.maxInt(i64)
    else
        attrs.expires;

    // The cap. See `lifetime_max_s`: a credential the server wanted to
    // live for eighty years lives for 400 days.
    const ceiling = std.math.add(i64, now, lifetime_max_s) catch std.math.maxInt(i64);
    const expires: ?i64 = if (asked) |when| @min(when, ceiling) else null;

    if (expires) |when| {
        if (when <= now) return error.CookieExpired;
    }

    return .{
        .name = attrs.name,
        .value = attrs.value,
        .domain = domain.domain,
        .path = path,
        .host_only = domain.host_only,
        .secure = attrs.secure,
        .http_only = attrs.http_only,
        .expires = expires,
    };
}

/// Whether a hop to `scheme` and `host` may carry a `Secure` cookie.
///
/// A `Secure` cookie is one the server said must never cross a cleartext
/// connection. `https` is such a connection. So is a hop to the loopback
/// address, which no other machine can read.
///
/// **The loopback rule is curl's, measured.** curl 8.21.0 sends a `Secure`
/// cookie from a jar over plain `http` to `127.0.0.1`, and withholds the
/// same cookie over plain `http` to a name that resolves to that same
/// address. RFC 6265bis calls loopback a potentially trustworthy origin
/// for that reason. zurl matches curl here so that a jar written against a
/// local test server behaves the same way under both programs.
///
/// Every other host over plain `http` gets nothing marked `Secure`.
pub fn secureContext(scheme: []const u8, host: []const u8) bool {
    if (std.ascii.eqlIgnoreCase(scheme, "https")) return true;
    if (std.ascii.eqlIgnoreCase(host, "localhost")) return true;
    if (std.mem.eql(u8, host, "::1")) return true;
    // The whole 127.0.0.0/8 block is loopback, and not the one address
    // most people type.
    const octets = ip4Octets(host) orelse return false;
    return octets[0] == 127;
}

/// One line of a Netscape cookie file, with every slice borrowed from the
/// line.
pub const JarLine = struct {
    domain: []const u8,
    /// Column two. True for a cookie that subdomains also get.
    ///
    /// **This column decides, and the leading dot does not.** Measured
    /// against curl 8.21.0: a line reading `example.test<TAB>TRUE<TAB>...`
    /// with no dot was sent to `www.example.test` and written back out as
    /// `.example.test`, so curl reads the column and normalises the dot on
    /// the way out.
    include_subdomains: bool,
    path: []const u8,
    secure: bool,
    /// Column five: when the cookie expires, in seconds since the epoch.
    /// Zero for a session cookie, which is what curl writes.
    expires: i64,
    name: []const u8,
    value: []const u8,
    http_only: bool,
};

/// Reads one line of a Netscape cookie file.
///
/// Returns null for a line this build does not read as a cookie: a
/// comment, an empty line, a line with the wrong number of columns, or a
/// line with a field past its bound. **A jar file is untrusted input.** It
/// may come from another program, from a shared directory, or from an
/// attacker who could write one file. So a line that does not parse is
/// dropped, and never guessed at.
///
/// `line` must carry no line ending. The caller splits the file.
///
/// The columns are tab separated and there are seven of them: the domain,
/// whether subdomains get it, the path, whether it is `Secure`, when it
/// expires, the name, and the value. A domain behind `#HttpOnly_` is a
/// `HttpOnly` cookie, which is curl's own convention.
pub fn parseJarLine(line: []const u8) ?JarLine {
    var rest = line;
    var http_only = false;

    if (std.mem.startsWith(u8, rest, http_only_prefix)) {
        http_only = true;
        rest = rest[http_only_prefix.len..];
    } else if (rest.len != 0 and rest[0] == '#') {
        return null;
    }
    if (rest.len == 0) return null;

    var columns: [7][]const u8 = undefined;
    var it = std.mem.splitScalar(u8, rest, '\t');
    for (&columns) |*column| column.* = it.next() orelse return null;
    // An eighth column means this line is not the shape this reader knows.
    // Reading the first seven of it would take a value from a file that
    // says something else.
    if (it.next() != null) return null;

    const domain = if (columns[0].len != 0 and columns[0][0] == '.') columns[0][1..] else columns[0];
    if (domain.len == 0 or domain.len > domain_len_max) return null;
    if (columns[2].len == 0 or columns[2].len > path_len_max) return null;
    if (columns[5].len == 0 or columns[5].len > name_len_max) return null;
    if (columns[6].len > value_len_max) return null;

    // A column that is not a number at all is a line this reader does not
    // know, and a number past `i64` is a file trying to overflow one.
    const expires = std.fmt.parseInt(i64, columns[4], 10) catch return null;

    return .{
        .domain = domain,
        .include_subdomains = std.ascii.eqlIgnoreCase(columns[1], "TRUE"),
        .path = columns[2],
        .secure = std.ascii.eqlIgnoreCase(columns[3], "TRUE"),
        .expires = expires,
        .name = columns[5],
        .value = columns[6],
        .http_only = http_only,
    };
}

/// Writes one line of a Netscape cookie file, with its line ending.
///
/// Measured against curl 8.21.0, which writes
/// `127.0.0.1<TAB>FALSE<TAB>/dir<TAB>FALSE<TAB>0<TAB>sess<TAB>abc123`. A
/// domain cookie gets the leading dot back, which is what curl writes for
/// every line whose second column is `TRUE`.
pub fn writeJarLine(w: *std.Io.Writer, line: JarLine) std.Io.Writer.Error!void {
    if (line.http_only) try w.writeAll(http_only_prefix);
    if (line.include_subdomains) try w.writeByte('.');
    try w.print("{s}\t{s}\t{s}\t{s}\t{d}\t{s}\t{s}\n", .{
        line.domain,
        if (line.include_subdomains) "TRUE" else "FALSE",
        line.path,
        if (line.secure) "TRUE" else "FALSE",
        line.expires,
        line.name,
        line.value,
    });
}

/// Whether a byte may appear in a cookie name or value on the wire.
///
/// **A cookie reaches a request header, so this is header injection
/// ground.** A CR or an LF in a value would put a header of the peer's
/// choosing on the wire, and a NUL would cut the head short. A jar file
/// can carry any byte at all, so this is checked on the way in and on the
/// way out.
///
/// The set is every printable ASCII byte and nothing else. RFC 6265 allows
/// a narrower set still, but a real server sends values outside it, and
/// curl passes those through. Refusing the control bytes is the part that
/// carries the security.
pub fn wireSafe(text: []const u8) bool {
    for (text) |byte| {
        if (!std.ascii.isPrint(byte)) return false;
        // A semicolon inside a value would read as the end of that cookie
        // and the start of another one, so a value holding one could add a
        // cookie the server never sent.
        if (byte == ';') return false;
    }
    return true;
}

/// Whether a domain or a path may reach the jar.
///
/// The same reason as `wireSafe`, and one more: a tab in either field
/// would write a jar line with an extra column, so a jar zurl wrote would
/// read back as a different cookie.
pub fn fieldSafe(text: []const u8) bool {
    for (text) |byte| {
        if (!std.ascii.isPrint(byte)) return false;
        if (byte == '\t' or byte == ';') return false;
    }
    return true;
}

/// The months, in the order `parseDate` numbers them.
const month_names = [_][]const u8{
    "jan", "feb", "mar", "apr", "may", "jun",
    "jul", "aug", "sep", "oct", "nov", "dec",
};

/// Reads a cookie date and returns it as seconds since the epoch, or null
/// when the text is not a date this build knows.
///
/// **Three formats reach this, and one algorithm reads all three.** RFC
/// 6265 section 5.1.1 says to split the text on delimiters and then look
/// for a time, a day, a month, and a year among the pieces, in any order.
/// That reads `Wed, 09 Jun 2100 10:18:14 GMT`, `Wednesday,
/// 09-Jun-00 10:18:14 GMT`, and `Wed Jun  9 10:18:14 2100` with no
/// per-format branch, which is why the specification wrote it that way.
///
/// A two-digit year is read the way section 5.1.1 asks: 70 through 99 is
/// the 1900s, and 0 through 69 is the 2000s.
///
/// Every date is read as UTC. A cookie date carries a zone name that RFC
/// 6265 tells a client to ignore, and every real server writes `GMT`.
///
/// Returns null rather than an error, because a date it cannot read is a
/// cookie with no expiry rather than a fault: RFC 6265 section 5.2.1 says
/// to ignore the attribute. A cookie with no expiry is a session cookie,
/// which is the shorter life of the two, so a misread date can never
/// lengthen one.
pub fn parseDate(text: []const u8) ?i64 {
    if (text.len > 128) return null;

    var hour: ?u32 = null;
    var minute: u32 = 0;
    var second: u32 = 0;
    var day: ?u32 = null;
    var month: ?u32 = null;
    var year: ?u32 = null;

    // The loop runs once for each piece, and every round consumes at least
    // one byte, so the bound above bounds this too.
    var rest = text;
    while (rest.len != 0) {
        while (rest.len != 0 and isDelimiter(rest[0])) rest = rest[1..];
        var end: usize = 0;
        while (end < rest.len and !isDelimiter(rest[end])) end += 1;
        const piece = rest[0..end];
        rest = rest[end..];
        if (piece.len == 0) continue;

        if (hour == null) {
            if (readTime(piece)) |time| {
                hour = time.hour;
                minute = time.minute;
                second = time.second;
                continue;
            }
        }
        if (day == null and piece.len <= 2 and allDigits(piece)) {
            day = std.fmt.parseInt(u32, piece, 10) catch continue;
            continue;
        }
        if (month == null) {
            if (readMonth(piece)) |number| {
                month = number;
                continue;
            }
        }
        if (year == null and piece.len >= 2 and piece.len <= 4 and allDigits(piece)) {
            year = std.fmt.parseInt(u32, piece, 10) catch continue;
            continue;
        }
    }

    var y = year orelse return null;
    const m = month orelse return null;
    const d = day orelse return null;
    const h = hour orelse return null;
    if (y >= 70 and y <= 99) y += 1900;
    if (y <= 69) y += 2000;

    if (d < 1 or d > 31) return null;
    if (h > 23 or minute > 59 or second > 59) return null;
    // A year before the epoch reads as a cookie that has already expired,
    // and a year past this is beyond any clock this program will see.
    if (y < 1601 or y > 9999) return null;

    const days = daysFromCivil(y, m, d);
    const seconds = @as(i64, days) * 86400 +
        @as(i64, h) * 3600 + @as(i64, minute) * 60 + @as(i64, second);
    return seconds;
}

fn isDelimiter(byte: u8) bool {
    if (byte == 0x09) return true;
    if (byte >= 0x20 and byte <= 0x2f) return true;
    if (byte >= 0x3b and byte <= 0x40) return true;
    if (byte >= 0x5b and byte <= 0x60) return true;
    if (byte >= 0x7b and byte <= 0x7e) return true;
    return false;
}

fn allDigits(text: []const u8) bool {
    if (text.len == 0) return false;
    for (text) |byte| {
        if (!std.ascii.isDigit(byte)) return false;
    }
    return true;
}

fn readTime(piece: []const u8) ?struct { hour: u32, minute: u32, second: u32 } {
    var it = std.mem.splitScalar(u8, piece, ':');
    const h = it.next() orelse return null;
    const m = it.next() orelse return null;
    const s = it.next() orelse return null;
    if (it.next() != null) return null;
    if (h.len < 1 or h.len > 2 or m.len < 1 or m.len > 2 or s.len < 1 or s.len > 2) return null;
    if (!allDigits(h) or !allDigits(m) or !allDigits(s)) return null;
    return .{
        .hour = std.fmt.parseInt(u32, h, 10) catch return null,
        .minute = std.fmt.parseInt(u32, m, 10) catch return null,
        .second = std.fmt.parseInt(u32, s, 10) catch return null,
    };
}

fn readMonth(piece: []const u8) ?u32 {
    if (piece.len < 3) return null;
    for (month_names, 0..) |name, index| {
        if (std.ascii.eqlIgnoreCase(piece[0..3], name)) return @intCast(index + 1);
    }
    return null;
}

/// Days from 1970-01-01 to `y`-`m`-`d`, by Howard Hinnant's `days_from_civil`.
///
/// The algorithm shifts the year so that March starts it, which puts the
/// leap day at the end and removes every special case for February. It is
/// exact for every year this function accepts.
fn daysFromCivil(y: u32, m: u32, d: u32) i64 {
    const year: i64 = @as(i64, y) - @intFromBool(m <= 2);
    const era: i64 = @divFloor(year, 400);
    const year_of_era: i64 = year - era * 400;
    const month: i64 = @intCast(m);
    const day: i64 = @intCast(d);
    const day_of_year: i64 = @divFloor(153 * (month + (if (month > 2) @as(i64, -3) else 9)) + 2, 5) + day - 1;
    const day_of_era: i64 = year_of_era * 365 + @divFloor(year_of_era, 4) -
        @divFloor(year_of_era, 100) + day_of_year;
    return era * 146097 + day_of_era - 719468;
}

const testing = std.testing;

test "a Set-Cookie with a name and a value alone parses to a session cookie" {
    const attrs = try parseSetCookie("sess=abc123");
    try testing.expectEqualStrings("sess", attrs.name);
    try testing.expectEqualStrings("abc123", attrs.value);
    try testing.expectEqual(@as(?[]const u8, null), attrs.domain);
    try testing.expectEqual(@as(?[]const u8, null), attrs.path);
    try testing.expectEqual(@as(?i64, null), attrs.expires);
    try testing.expect(!attrs.secure);
    try testing.expect(!attrs.http_only);
}

test "a Set-Cookie with no equals sign sets no cookie, the way curl drops it" {
    try testing.expectError(error.CookieMalformed, parseSetCookie("novalue"));
    try testing.expectError(error.CookieMalformed, parseSetCookie("  ; Path=/"));
    try testing.expectError(error.CookieMalformed, parseSetCookie("=onlyvalue"));
}

test "a Set-Cookie with an empty value is a cookie, which curl keeps" {
    const attrs = try parseSetCookie("emptyval=");
    try testing.expectEqualStrings("emptyval", attrs.name);
    try testing.expectEqualStrings("", attrs.value);
}

test "every attribute of one Set-Cookie reaches the parse" {
    const attrs = try parseSetCookie(
        "id=v; Domain=.example.test; Path=/dir; Secure; HttpOnly; Max-Age=3600",
    );
    try testing.expectEqualStrings("id", attrs.name);
    try testing.expectEqualStrings("v", attrs.value);
    // The leading dot comes off, which RFC 6265 section 5.2.3 asks for.
    try testing.expectEqualStrings("example.test", attrs.domain.?);
    try testing.expectEqualStrings("/dir", attrs.path.?);
    try testing.expect(attrs.secure);
    try testing.expect(attrs.http_only);
    try testing.expectEqual(@as(?i64, 3600), attrs.max_age);
}

test "an attribute this build does not know is dropped and the cookie stays" {
    const attrs = try parseSetCookie("id=v; SameSite=Lax; Priority=High; Partitioned");
    try testing.expectEqualStrings("id", attrs.name);
    try testing.expectEqualStrings("v", attrs.value);
}

test "a Path that does not start with a slash reads as no Path at all" {
    const attrs = try parseSetCookie("id=v; Path=dir");
    try testing.expectEqual(@as(?[]const u8, null), attrs.path);
}

test "a Set-Cookie past the header bound is refused before any field is read" {
    var buffer: [set_cookie_len_max + 16]u8 = undefined;
    @memset(&buffer, 'a');
    @memcpy(buffer[0..3], "a=b");
    try testing.expectError(error.CookieTooLarge, parseSetCookie(&buffer));
}

test "a name or a value past its own bound is refused" {
    var buffer: [name_len_max + 32]u8 = undefined;
    @memset(&buffer, 'n');
    buffer[name_len_max + 1] = '=';
    try testing.expectError(error.CookieTooLarge, parseSetCookie(buffer[0 .. name_len_max + 3]));
}

test "a cookie set by one host never reaches another host" {
    // The whole point of the domain rule: `a.example.test` and
    // `b.example.test` are two sites, and a cookie of one is not a cookie
    // of the other.
    try testing.expect(domainMatches("a.example.test", "a.example.test", true));
    try testing.expect(!domainMatches("b.example.test", "a.example.test", true));
    try testing.expect(!domainMatches("b.example.test", "a.example.test", false));
}

test "a domain cookie reaches a subdomain and a host-only cookie does not" {
    try testing.expect(domainMatches("www.example.test", "example.test", false));
    try testing.expect(domainMatches("deep.www.example.test", "example.test", false));
    try testing.expect(!domainMatches("www.example.test", "example.test", true));
    // The dot has to be there. `notexample.test` is a different site.
    try testing.expect(!domainMatches("notexample.test", "example.test", false));
}

test "a domain match ignores case, because DNS names do" {
    try testing.expect(domainMatches("WWW.Example.Test", "example.test", false));
    try testing.expect(domainMatches("Example.Test", "example.TEST", true));
}

test "an address host matches only itself, whatever the host-only flag says" {
    try testing.expect(domainMatches("127.0.0.1", "127.0.0.1", true));
    try testing.expect(!domainMatches("127.0.0.1", "0.0.1", false));
    try testing.expect(!domainMatches("1.2.3.4", "2.3.4", false));
}

test "a path cookie reaches what sits under it and nothing beside it" {
    try testing.expect(pathMatches("/dir", "/dir"));
    try testing.expect(pathMatches("/dir/page", "/dir"));
    try testing.expect(pathMatches("/dir/deep/page", "/dir"));
    try testing.expect(!pathMatches("/directory", "/dir"));
    try testing.expect(!pathMatches("/", "/dir"));
    try testing.expect(pathMatches("/anything", "/"));
}

test "the default path is the request path up to its last slash" {
    try testing.expectEqualStrings("/dir", defaultPath("/dir/page"));
    try testing.expectEqualStrings("/", defaultPath("/page"));
    try testing.expectEqualStrings("/", defaultPath("/"));
    try testing.expectEqualStrings("/a/b", defaultPath("/a/b/c"));
    try testing.expectEqualStrings("/", defaultPath(""));
    try testing.expectEqualStrings("/", defaultPath("noslash"));
}

test "a response cannot set a cookie for a host it does not control" {
    // The headline case. `evil.test` names `bank.test` and gets nothing.
    try testing.expectError(error.CookieDomainNotOwned, resolveDomain("evil.test", "bank.test"));
    try testing.expectError(error.CookieDomainNotOwned, resolveDomain("a.example.test", "b.example.test"));
    // A host cannot claim a domain below itself either.
    try testing.expectError(
        error.CookieDomainNotOwned,
        resolveDomain("www.example.test", "deep.www.example.test"),
    );
}

test "nothing may set a cookie on a single-label domain" {
    try testing.expectError(error.CookiePublicSuffix, resolveDomain("a.com", "com"));
    try testing.expectError(error.CookiePublicSuffix, resolveDomain("host.localhost", "localhost"));
}

test "nothing may set a cookie on a public suffix of more than one label" {
    // The case the single-label floor could not name. Measured against
    // curl 8.21.0, which refuses each of these through libpsl.
    try testing.expectError(error.CookiePublicSuffix, resolveDomain("www.example.co.uk", "co.uk"));
    try testing.expectError(error.CookiePublicSuffix, resolveDomain("www.example.com.au", "com.au"));
    try testing.expectError(error.CookiePublicSuffix, resolveDomain("a.b.github.io", "github.io"));
    // A wildcard rule, `*.ck`, and a rule three labels deep.
    try testing.expectError(error.CookiePublicSuffix, resolveDomain("www.foo.ck", "foo.ck"));
    try testing.expectError(error.CookiePublicSuffix, resolveDomain("www.t.k12.ak.us", "k12.ak.us"));
}

test "an ordinary domain under a public suffix still takes a cookie" {
    // Over-refusing breaks real sites, so the passing cases matter as
    // much as the refusals. Measured against curl 8.21.0, which keeps
    // every one of these.
    for ([_][2][]const u8{
        .{ "www.example.co.uk", "example.co.uk" },
        .{ "a.b.github.io", "b.github.io" },
        .{ "www.t.k12.ak.us", "t.k12.ak.us" },
        .{ "www.example.com", "example.com" },
        // An exception rule takes `www.ck` back out of `*.ck`, so a host
        // under it may set a cookie for it.
        .{ "deep.www.ck", "www.ck" },
    }) |pair| {
        const resolved = try resolveDomain(pair[0], pair[1]);
        try testing.expectEqualStrings(pair[1], resolved.domain);
        try testing.expect(!resolved.host_only);
    }
}

test "a domain zurl cannot represent is refused rather than guessed at" {
    // No IDN. The list holds A-labels, so a U-label is refused. The
    // A-label of the same name is matched. `公司.cn` is `xn--55qx5d.cn`.
    try testing.expectError(
        error.CookiePublicSuffix,
        resolveDomain("www.example.\u{516C}\u{53F8}.cn", "example.\u{516C}\u{53F8}.cn"),
    );
    try testing.expectError(
        error.CookiePublicSuffix,
        resolveDomain("www.example.xn--55qx5d.cn", "xn--55qx5d.cn"),
    );
    const under = try resolveDomain("www.example.xn--55qx5d.cn", "example.xn--55qx5d.cn");
    try testing.expectEqualStrings("example.xn--55qx5d.cn", under.domain);
}

test "an exact domain match is host-only, which is curl 8.22.0's rule" {
    const exact = try resolveDomain("www.example.test", "www.example.test");
    try testing.expectEqualStrings("www.example.test", exact.domain);
    try testing.expect(exact.host_only);
    // And so the cookie does not reach a deeper subdomain.
    try testing.expect(!domainMatches("deep.www.example.test", exact.domain, exact.host_only));
}

test "a parent domain gives a cookie that subdomains share" {
    const parent = try resolveDomain("www.example.test", "example.test");
    try testing.expectEqualStrings("example.test", parent.domain);
    try testing.expect(!parent.host_only);
    try testing.expect(domainMatches("other.example.test", parent.domain, parent.host_only));
}

test "no Domain attribute gives a host-only cookie on the host itself" {
    const none = try resolveDomain("www.example.test", null);
    try testing.expectEqualStrings("www.example.test", none.domain);
    try testing.expect(none.host_only);
}

test "an address host takes a host-only cookie and refuses any other domain" {
    const own = try resolveDomain("127.0.0.1", "127.0.0.1");
    try testing.expect(own.host_only);
    try testing.expectError(error.CookieDomainNotOwned, resolveDomain("127.0.0.1", "example.test"));
    try testing.expectError(error.CookieDomainNotOwned, resolveDomain("127.0.0.1", "0.0.1"));
}

/// A url for a test, parsed from text this file writes.
fn testUrl(text: []const u8) Url {
    return @import("url.zig").parse(text) catch unreachable;
}

test "Max-Age outranks Expires, which is what curl stores" {
    const attrs = try parseSetCookie("both=b1; Max-Age=7200; Expires=Wed, 09 Jun 2100 10:18:14 GMT");
    const cookie = try resolve(attrs, testUrl("http://www.example.test/dir/page"), 1000);
    try testing.expectEqual(@as(?i64, 1000 + 7200), cookie.expires);
}

test "a cookie asking for the year 2100 gets 400 days, the way curl caps it" {
    const attrs = try parseSetCookie("ex=e1; Expires=Wed, 09 Jun 2100 10:18:14 GMT");
    const cookie = try resolve(attrs, testUrl("http://www.example.test/"), 1000);
    try testing.expectEqual(@as(?i64, 1000 + lifetime_max_s), cookie.expires);

    // The same cap through Max-Age, and a life under the cap is untouched.
    const long = try parseSetCookie("ex=e1; Max-Age=999999999");
    const capped = try resolve(long, testUrl("http://www.example.test/"), 1000);
    try testing.expectEqual(@as(?i64, 1000 + lifetime_max_s), capped.expires);

    const short = try parseSetCookie("ex=e1; Max-Age=3600");
    const kept = try resolve(short, testUrl("http://www.example.test/"), 1000);
    try testing.expectEqual(@as(?i64, 4600), kept.expires);
}

test "a cookie whose expiry has passed is refused rather than stored" {
    const attrs = try parseSetCookie("gone=g1; Expires=Wed, 09 Jun 2001 10:18:14 GMT");
    try testing.expectError(
        error.CookieExpired,
        resolve(attrs, testUrl("http://www.example.test/"), 1788586466),
    );
    const zero = try parseSetCookie("gone=g1; Max-Age=0");
    try testing.expectError(
        error.CookieExpired,
        resolve(zero, testUrl("http://www.example.test/"), 1000),
    );
}

test "a resolved cookie takes the default path of the request" {
    const attrs = try parseSetCookie("sess=abc123");
    const cookie = try resolve(attrs, testUrl("http://127.0.0.1:18080/dir/page"), 1000);
    try testing.expectEqualStrings("127.0.0.1", cookie.domain);
    try testing.expectEqualStrings("/dir", cookie.path);
    try testing.expect(cookie.host_only);
    try testing.expectEqual(@as(?i64, null), cookie.expires);
}

test "a Secure cookie never crosses plain http to a host off the loopback" {
    try testing.expect(!secureContext("http", "www.example.test"));
    try testing.expect(secureContext("https", "www.example.test"));
}

test "loopback counts as a secure context, which is what curl measures" {
    try testing.expect(secureContext("http", "127.0.0.1"));
    try testing.expect(secureContext("http", "127.9.9.9"));
    try testing.expect(secureContext("http", "localhost"));
    try testing.expect(secureContext("http", "::1"));
    try testing.expect(!secureContext("http", "128.0.0.1"));
}

test "a jar line reads the seven columns curl writes" {
    const line = parseJarLine("127.0.0.1\tFALSE\t/dir\tFALSE\t0\tsess\tabc123").?;
    try testing.expectEqualStrings("127.0.0.1", line.domain);
    try testing.expect(!line.include_subdomains);
    try testing.expectEqualStrings("/dir", line.path);
    try testing.expect(!line.secure);
    try testing.expectEqual(@as(i64, 0), line.expires);
    try testing.expectEqualStrings("sess", line.name);
    try testing.expectEqualStrings("abc123", line.value);
    try testing.expect(!line.http_only);
}

test "the HttpOnly prefix is read, and an ordinary comment is not a cookie" {
    const line = parseJarLine("#HttpOnly_www.example.test\tFALSE\t/\tFALSE\t0\tho\thv").?;
    try testing.expect(line.http_only);
    try testing.expectEqualStrings("www.example.test", line.domain);
    try testing.expectEqual(@as(?JarLine, null), parseJarLine("# Netscape HTTP Cookie File"));
    try testing.expectEqual(@as(?JarLine, null), parseJarLine(""));
}

test "a jar line with the wrong number of columns is dropped, not guessed at" {
    try testing.expectEqual(@as(?JarLine, null), parseJarLine("a\tb\tc"));
    try testing.expectEqual(
        @as(?JarLine, null),
        parseJarLine("d\tFALSE\t/\tFALSE\t0\tn\tv\textra"),
    );
    // A fifth column that is not a number, and one that would overflow.
    try testing.expectEqual(@as(?JarLine, null), parseJarLine("d\tFALSE\t/\tFALSE\tsoon\tn\tv"));
    try testing.expectEqual(
        @as(?JarLine, null),
        parseJarLine("d\tFALSE\t/\tFALSE\t99999999999999999999999\tn\tv"),
    );
}

test "the second column decides a domain cookie, and the leading dot does not" {
    // Measured against curl 8.21.0: a line with TRUE and no dot was sent to
    // a subdomain, and written back out with the dot.
    const dotless = parseJarLine("example.test\tTRUE\t/\tFALSE\t0\tn\tv").?;
    try testing.expect(dotless.include_subdomains);
    try testing.expectEqualStrings("example.test", dotless.domain);
    const dotted = parseJarLine(".example.test\tTRUE\t/\tFALSE\t0\tn\tv").?;
    try testing.expectEqualStrings("example.test", dotted.domain);
}

test "a jar line round trips through the writer byte for byte" {
    const text = "127.0.0.1\tFALSE\t/dir\tFALSE\t0\tsess\tabc123\n";
    const line = parseJarLine(text[0 .. text.len - 1]).?;
    var buffer: [256]u8 = undefined;
    var writer: std.Io.Writer = .fixed(&buffer);
    try writeJarLine(&writer, line);
    try testing.expectEqualStrings(text, writer.buffered());
}

test "a domain cookie and a HttpOnly cookie write the prefixes curl writes" {
    var buffer: [256]u8 = undefined;
    var writer: std.Io.Writer = .fixed(&buffer);
    try writeJarLine(&writer, .{
        .domain = "example.test",
        .include_subdomains = true,
        .path = "/",
        .secure = true,
        .expires = 2000000000,
        .name = "n",
        .value = "v",
        .http_only = true,
    });
    try testing.expectEqualStrings(
        "#HttpOnly_.example.test\tTRUE\t/\tTRUE\t2000000000\tn\tv\n",
        writer.buffered(),
    );
}

test "a CR, an LF, a NUL, or a semicolon in a cookie value is refused" {
    try testing.expect(wireSafe("abc123"));
    try testing.expect(!wireSafe("a\r\nX-Injected: yes"));
    try testing.expect(!wireSafe("a\nb"));
    try testing.expect(!wireSafe("a\x00b"));
    try testing.expect(!wireSafe("a;b=c"));
    try testing.expect(!wireSafe("a\tb"));
}

test "a tab in a domain or a path is refused, so a jar line keeps its columns" {
    try testing.expect(fieldSafe("/dir/page"));
    try testing.expect(!fieldSafe("/dir\tFALSE\t/"));
    try testing.expect(!fieldSafe("a\nb"));
}

test "the three cookie date formats all read to the same instant" {
    const want: i64 = 1623233894; // 2021-06-09 10:18:14 UTC
    try testing.expectEqual(@as(?i64, want), parseDate("Wed, 09 Jun 2021 10:18:14 GMT"));
    try testing.expectEqual(@as(?i64, want), parseDate("Wednesday, 09-Jun-21 10:18:14 GMT"));
    try testing.expectEqual(@as(?i64, want), parseDate("Wed Jun  9 10:18:14 2021"));
}

test "the epoch itself and a leap day read exactly" {
    try testing.expectEqual(@as(?i64, 0), parseDate("Thu, 01 Jan 1970 00:00:00 GMT"));
    // 2000-02-29 is a leap day of a century that is a leap year.
    try testing.expectEqual(@as(?i64, 951782400), parseDate("Tue, 29 Feb 2000 00:00:00 GMT"));
}

test "a date this build cannot read is null, which leaves a session cookie" {
    try testing.expectEqual(@as(?i64, null), parseDate(""));
    try testing.expectEqual(@as(?i64, null), parseDate("not a date at all"));
    try testing.expectEqual(@as(?i64, null), parseDate("Wed, 09 Jun 2021 GMT"));
    try testing.expectEqual(@as(?i64, null), parseDate("Wed, 99 Jun 2021 10:18:14 GMT"));
    try testing.expectEqual(@as(?i64, null), parseDate("Wed, 09 Jun 2021 99:18:14 GMT"));
    var long: [200]u8 = undefined;
    @memset(&long, 'x');
    try testing.expectEqual(@as(?i64, null), parseDate(&long));
}

test "a two-digit year splits at 69, the way RFC 6265 says" {
    const y2069 = parseDate("Wed, 01 Jan 69 00:00:00 GMT").?;
    const y1970 = parseDate("Wed, 01 Jan 70 00:00:00 GMT").?;
    try testing.expectEqual(@as(i64, 0), y1970);
    try testing.expect(y2069 > y1970);
}
